openapi: 3.0.3
info:
  title: Tekton Hub
  description: HTTP services for managing Tekton Hub
  version: "1.0"
servers:
- url: https://api.hub.tekton.dev
paths:
  /:
    get:
      tags:
      - status
      summary: Status status
      description: Return status of the services
      operationId: status#Status
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponseBody'
              example:
                services:
                - error: unable to reach db
                  name: api
                  status: ok
                - error: unable to reach db
                  name: api
                  status: ok
                - error: unable to reach db
                  name: api
                  status: ok
                - error: unable to reach db
                  name: api
                  status: ok
  /catalog/{catalogName}/error:
    get:
      tags:
      - catalog
      summary: CatalogError catalog
      description: List all errors occurred refreshing a catalog
      operationId: catalog#CatalogError
      parameters:
      - name: catalogName
        in: path
        description: Name of catalog
        required: true
        schema:
          type: string
          description: Name of catalog
          example: tekton
        example: tekton
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CatalogErrorResponseBody'
              example:
                data:
                - errors:
                  - Resource tekton.dev/v1beta1, Kind=Task - buildah has no display
                    name
                  - Resource tekton.dev/v1beta1, Kind=task - curl has no display name
                  type: warning
                - errors:
                  - Resource tekton.dev/v1beta1, Kind=Task - buildah has no display
                    name
                  - Resource tekton.dev/v1beta1, Kind=task - curl has no display name
                  type: warning
        "500":
          description: Internal Server Error response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
      security:
      - jwt_header_Authorization:
        - rating:read
        - rating:write
        - agent:create
        - catalog:refresh
        - config:refresh
        - refresh:token
  /catalog/{catalogName}/refresh:
    post:
      tags:
      - catalog
      summary: Refresh catalog
      description: Refresh a Catalog by it's name
      operationId: catalog#Refresh
      parameters:
      - name: catalogName
        in: path
        description: Name of catalog
        required: true
        schema:
          type: string
          description: Name of catalog
          example: tekton
        example: tekton
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
              example:
                catalogName: tekton
                id: 1
                status: queued
        "404":
          description: Not Found response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "500":
          description: Internal Server Error response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
      security:
      - jwt_header_Authorization:
        - rating:read
        - rating:write
        - agent:create
        - catalog:refresh
        - config:refresh
        - refresh:token
  /catalog/refresh:
    post:
      tags:
      - catalog
      summary: RefreshAll catalog
      description: Refresh all catalogs
      operationId: catalog#RefreshAll
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Job'
                example:
                - catalogName: tekton
                  id: 1
                  status: queued
                - catalogName: tekton
                  id: 1
                  status: queued
                - catalogName: tekton
                  id: 1
                  status: queued
                - catalogName: tekton
                  id: 1
                  status: queued
              example:
              - catalogName: tekton
                id: 1
                status: queued
              - catalogName: tekton
                id: 1
                status: queued
        "500":
          description: Internal Server Error response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
      security:
      - jwt_header_Authorization:
        - rating:read
        - rating:write
        - agent:create
        - catalog:refresh
        - config:refresh
        - refresh:token
  /categories:
    get:
      tags:
      - category
      summary: list category
      description: List all categories along with their tags sorted by name
      operationId: category#list
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListResponseBody'
              example:
                data:
                - id: 1
                  name: Image Builder
                - id: 1
                  name: Image Builder
                - id: 1
                  name: Image Builder
                - id: 1
                  name: Image Builder
        "500":
          description: Internal Server Error response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
  /resource/{id}/rating:
    get:
      tags:
      - rating
      summary: Get rating
      description: Find user's rating for a resource
      operationId: rating#Get
      parameters:
      - name: id
        in: path
        description: ID of a resource
        required: true
        schema:
          type: integer
          description: ID of a resource
          example: 17081788299688252022
        example: 11089527418313215274
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetResponseBody'
              example:
                rating: 4
        "401":
          description: Unauthorized response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "403":
          description: Forbidden response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "404":
          description: Not Found response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "500":
          description: Internal Server Error response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
      security:
      - jwt_header_Authorization:
        - rating:read
        - rating:write
        - agent:create
        - catalog:refresh
        - config:refresh
        - refresh:token
    put:
      tags:
      - rating
      summary: Update rating
      description: Update user's rating for a resource
      operationId: rating#Update
      parameters:
      - name: id
        in: path
        description: ID of a resource
        required: true
        schema:
          type: integer
          description: ID of a resource
          example: 9739613307880178607
        example: 2070151992422837927
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateRequestBody'
            example:
              rating: 0
      responses:
        "200":
          description: OK response.
        "401":
          description: Unauthorized response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "403":
          description: Forbidden response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "404":
          description: Not Found response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "500":
          description: Internal Server Error response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
      security:
      - jwt_header_Authorization:
        - rating:read
        - rating:write
        - agent:create
        - catalog:refresh
        - config:refresh
        - refresh:token
  /schema/swagger.json:
    get:
      tags:
      - swagger
      summary: Download docs/openapi3.json
      description: JSON document containing the API swagger definition
      operationId: swagger#/schema/swagger.json
      responses:
        "200":
          description: File downloaded
  /system/config/refresh:
    post:
      tags:
      - admin
      summary: RefreshConfig admin
      description: Refresh the changes in config file
      operationId: admin#RefreshConfig
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RefreshConfigResponseBody'
              example:
                checksum: 41ba391c8baf1fcd3c62c11272b913dc6613f4cf3b1833cfbb32431dc4384c93
        "401":
          description: Unauthorized response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "403":
          description: Forbidden response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "500":
          description: Internal Server Error response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
      security:
      - jwt_header_Authorization:
        - rating:read
        - rating:write
        - agent:create
        - catalog:refresh
        - config:refresh
        - refresh:token
  /system/user/agent:
    put:
      tags:
      - admin
      summary: UpdateAgent admin
      description: Create or Update an agent user with required scopes
      operationId: admin#UpdateAgent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAgentRequestBody'
            example:
              name: abc
              scopes:
              - catalog-refresh
              - agent:create
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateAgentResponseBody'
              example:
                token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1Nzc4ODAzMDAsImlhdCI6MTU3Nzg4MDAwMCwiaWQiOjExLCJpc3MiOiJUZWt0b24gSHViIiwic2NvcGVzIjpbInJhdGluZzpyZWFkIiwicmF0aW5nOndyaXRlIiwiYWdlbnQ6Y3JlYXRlIl0sInR5cGUiOiJhY2Nlc3MtdG9rZW4ifQ.6pDmziSKkoSqI1f0rc4-AqVdcfY0Q8wA-tSLzdTCLgM
        "400":
          description: Bad Request response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "401":
          description: Unauthorized response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "403":
          description: Forbidden response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "500":
          description: Internal Server Error response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
      security:
      - jwt_header_Authorization:
        - rating:read
        - rating:write
        - agent:create
        - catalog:refresh
        - config:refresh
        - refresh:token
  /v1:
    get:
      tags:
      - status
      summary: Status status
      description: Return status of the services
      operationId: status#Status#1
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponseBody'
              example:
                services:
                - error: unable to reach db
                  name: api
                  status: ok
                - error: unable to reach db
                  name: api
                  status: ok
                - error: unable to reach db
                  name: api
                  status: ok
                - error: unable to reach db
                  name: api
                  status: ok
  /v1/categories:
    get:
      tags:
      - category
      summary: list category
      description: List all categories along with their tags sorted by name
      operationId: category#list#1
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListResponseBody'
              example:
                data:
                - id: 1
                  name: Image Builder
                - id: 1
                  name: Image Builder
                - id: 1
                  name: Image Builder
                - id: 1
                  name: Image Builder
        "500":
          description: Internal Server Error response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
components:
  schemas:
    CatalogErrorResponseBody:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/CatalogErrors'
          description: Catalog errors
          example:
          - errors:
            - Resource tekton.dev/v1beta1, Kind=Task - buildah has no display name
            - Resource tekton.dev/v1beta1, Kind=task - curl has no display name
            type: warning
          - errors:
            - Resource tekton.dev/v1beta1, Kind=Task - buildah has no display name
            - Resource tekton.dev/v1beta1, Kind=task - curl has no display name
            type: warning
          - errors:
            - Resource tekton.dev/v1beta1, Kind=Task - buildah has no display name
            - Resource tekton.dev/v1beta1, Kind=task - curl has no display name
            type: warning
          - errors:
            - Resource tekton.dev/v1beta1, Kind=Task - buildah has no display name
            - Resource tekton.dev/v1beta1, Kind=task - curl has no display name
            type: warning
      example:
        data:
        - errors:
          - Resource tekton.dev/v1beta1, Kind=Task - buildah has no display name
          - Resource tekton.dev/v1beta1, Kind=task - curl has no display name
          type: warning
        - errors:
          - Resource tekton.dev/v1beta1, Kind=Task - buildah has no display name
          - Resource tekton.dev/v1beta1, Kind=task - curl has no display name
          type: warning
      required:
      - data
    CatalogErrors:
      type: object
      properties:
        errors:
          type: array
          items:
            type: string
            example: Et nihil aut.
          description: Catalog Error message
          example:
          - Resource tekton.dev/v1beta1, Kind=Task - buildah has no display name
          - Resource tekton.dev/v1beta1, Kind=task - curl has no display name
        type:
          type: string
          description: Catalog Errror type
          example: warning
      description: CatalogErrors define the errors that occurred during catalog refresh
      example:
        errors:
        - Resource tekton.dev/v1beta1, Kind=Task - buildah has no display name
        - Resource tekton.dev/v1beta1, Kind=task - curl has no display name
        type: warning
      required:
      - type
      - errors
    Category:
      type: object
      properties:
        id:
          type: integer
          description: ID is the unique id of the category
          example: 1
        name:
          type: string
          description: Name of category
          example: Image Builder
      example:
        id: 1
        name: Image Builder
      required:
      - id
      - name
    Error:
      type: object
      properties:
        fault:
          type: boolean
          description: Is the error a server-side fault?
          example: false
        id:
          type: string
          description: ID is a unique identifier for this particular occurrence of
            the problem.
          example: 123abc
        message:
          type: string
          description: Message is a human-readable explanation specific to this occurrence
            of the problem.
          example: parameter 'p' must be an integer
        name:
          type: string
          description: Name is the name of this class of errors.
          example: bad_request
        temporary:
          type: boolean
          description: Is the error temporary?
          example: false
        timeout:
          type: boolean
          description: Is the error a timeout?
          example: true
      description: Invalid request body
      example:
        id: 3F1FKVRR
        message: Value of ID must be an integer
        name: bad_request
      required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
    GetResponseBody:
      type: object
      properties:
        rating:
          type: integer
          description: User rating for resource
          example: 4
          format: int64
      example:
        rating: 4
      required:
      - rating
    HubService:
      type: object
      properties:
        error:
          type: string
          description: Details of the error if any
          example: unable to reach db
        name:
          type: string
          description: Name of the service
          example: api
        status:
          type: string
          description: Status of the service
          example: ok
          enum:
          - ok
          - error
      description: Describes the services and their status
      example:
        error: unable to reach db
        name: api
        status: ok
      required:
      - name
      - status
    Job:
      type: object
      properties:
        catalogName:
          type: string
          description: Name of the catalog
          example: tekton
        id:
          type: integer
          description: id of the job
          example: 1
        status:
          type: string
          description: status of the job
          example: queued
      example:
        catalogName: tekton
        id: 1
        status: queued
      required:
      - id
      - catalogName
      - status
    ListResponseBody:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Category'
          example:
          - id: 1
            name: Image Builder
          - id: 1
            name: Image Builder
      example:
        data:
        - id: 1
          name: Image Builder
        - id: 1
          name: Image Builder
        - id: 1
          name: Image Builder
    RefreshConfigResponseBody:
      type: object
      properties:
        checksum:
          type: string
          description: Config file checksum
          example: 41ba391c8baf1fcd3c62c11272b913dc6613f4cf3b1833cfbb32431dc4384c93
      example:
        checksum: 41ba391c8baf1fcd3c62c11272b913dc6613f4cf3b1833cfbb32431dc4384c93
      required:
      - checksum
    StatusResponseBody:
      type: object
      properties:
        services:
          type: array
          items:
            $ref: '#/components/schemas/HubService'
          description: List of services and their status
          example:
          - error: unable to reach db
            name: api
            status: ok
          - error: unable to reach db
            name: api
            status: ok
      example:
        services:
        - error: unable to reach db
          name: api
          status: ok
        - error: unable to reach db
          name: api
          status: ok
        - error: unable to reach db
          name: api
          status: ok
    UpdateAgentRequestBody:
      type: object
      properties:
        name:
          type: string
          description: Name of Agent
          example: abc
        scopes:
          type: array
          items:
            type: string
            example: Voluptas beatae id qui.
          description: Scopes required for Agent
          example:
          - catalog-refresh
          - agent:create
      example:
        name: abc
        scopes:
        - catalog-refresh
        - agent:create
      required:
      - name
      - scopes
    UpdateAgentResponseBody:
      type: object
      properties:
        token:
          type: string
          description: Agent JWT
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1Nzc4ODAzMDAsImlhdCI6MTU3Nzg4MDAwMCwiaWQiOjExLCJpc3MiOiJUZWt0b24gSHViIiwic2NvcGVzIjpbInJhdGluZzpyZWFkIiwicmF0aW5nOndyaXRlIiwiYWdlbnQ6Y3JlYXRlIl0sInR5cGUiOiJhY2Nlc3MtdG9rZW4ifQ.6pDmziSKkoSqI1f0rc4-AqVdcfY0Q8wA-tSLzdTCLgM
      example:
        token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1Nzc4ODAzMDAsImlhdCI6MTU3Nzg4MDAwMCwiaWQiOjExLCJpc3MiOiJUZWt0b24gSHViIiwic2NvcGVzIjpbInJhdGluZzpyZWFkIiwicmF0aW5nOndyaXRlIiwiYWdlbnQ6Y3JlYXRlIl0sInR5cGUiOiJhY2Nlc3MtdG9rZW4ifQ.6pDmziSKkoSqI1f0rc4-AqVdcfY0Q8wA-tSLzdTCLgM
      required:
      - token
    UpdateRequestBody:
      type: object
      properties:
        rating:
          type: integer
          description: User rating for resource
          example: 2
          minimum: 0
          maximum: 5
      example:
        rating: 3
      required:
      - rating
  securitySchemes:
    jwt_header_Authorization:
      type: http
      description: Secures endpoint by requiring a valid JWT retrieved via the /auth/login
        endpoint.
      scheme: bearer
